AspCyber/AspCyber/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AspCyber.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AspCyber/AspCyber/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspCyber.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AspCyber/AspCyber/Pages/List.cshtml.cs
using AspCyber.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AspCyber.Pages
{
    [Authorize(Roles = "Admin")]
    public class ListModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        public class UserRoleView
        {
            public string UserEmail { get; set; }
            public IList<string> Roles { get; set; }
        }

        [BindProperty]
        public IList<UserRoleView> model {get;set;} = new List<UserRoleView>();

        private readonly UserManager<IdentityUser> _userManager;

        public ListModel(UserManager<IdentityUser> userManager, ApplicationDbContext context)
        {
            _userManager =  userManager;
            _context = context;
        }

       
        public async Task<IActionResult> OnGetAsync()
        {
            var users = await _userManager.Users.ToListAsync();

            foreach (IdentityUser user in users )
            {
                UserRoleView identityUser = new UserRoleView()
                {
                    UserEmail = user.Email,
                    Roles = await _userManager.GetRolesAsync(user)
                    
                };
                model.Add(identityUser);
            }
            return Page();
        
        }
        [HttpPost]
        public async Task<IActionResult> OnPostDeleteUser(string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
                var userLog = new UserLog
                {
                    UserName = User.Identity.Name,
                    Timestamp = DateTime.Now,
                    Action = "Delete user" + " " + user.Email,
                };
                _context.UserLogs.Add(userLog);
                await _context.SaveChangesAsync();

                if (result.Succeeded)
                {
                    return RedirectToPage("List");
                }
                else
                {
                    
                     return Page();
                }
            }
            return Page();

            //return RedirectToPage("List");
        }
        [HttpPost]

        public async Task<IActionResult> OnPostLockUser(string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user != null)
            {
                
                user.LockoutEnd = DateTime.Now.AddDays(7);

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    
                    return RedirectToPage("List"); 
                }
                else
                {
                    
                    return Page();
                }
            }

            
            return RedirectToPage("List");
        }

        [HttpPost]

        public async Task<IActionResult> OnPostUnlock(string email)
        {
            var user = await _userManager.FindByEmailAsync(email);
            if (user != null)
            {

                user.LockoutEnd = DateTime.Now;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {

                    return RedirectToPage("List");
                }
                else
                {

                    return Page();
                }
            }


            return RedirectToPage("List");
        }
    }
}

AspCyber/AspCyber/Pages/Logs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using AspCyber.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using AspCyber.Data;

namespace AspCyber.Pages
{
    [Authorize(Roles = "Admin")]
    public class LogsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public LogsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<UserLog> UserLogs { get; set; }

        public async Task OnGetAsync()
        {
            UserLogs = await _context.UserLogs.ToListAsync();
        }
    }
}

AspCyber/AspCyber/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspCyber.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AspCyber/AspCyber/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspCyber/AspCyber/Pages/List.cshtml
@page
@model ListModel


@foreach (var item in Model.model)
{
    <div>
        <div>Email: @item.UserEmail</div>
        <ul>
            @foreach (var role in item.Roles)
            {
                <li>Role: @role</li>

            }
        </ul>
        <div>
            <form method="post" asp-page-handler="DeleteUser" asp-route-email="@item.UserEmail">
                <button type="submit">Delete</button>
            </form>
        </div>
        <div>
            <form method="post" asp-page-handler="LockUser" asp-route-email="@item.UserEmail">
                <button type="submit">Lock 7 Days</button>
            </form>
        </div>
        <div>
            <form method="post" asp-page-handler="Unlock" asp-route-email="@item.UserEmail">
                <button type="submit">Unlock</button>
            </form>
        </div>
       

    </div>

}

AspCyber/AspCyber/Pages/Logs.cshtml
@page
@model LogsModel
@{
    ViewData["Title"] = "User Logs";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
        <tr>
            <th>User Name</th>
            <th>Action</th>
            <th>Timestamp</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model.UserLogs)
        {
            <tr>
                <td>@log.UserName</td>
                <td>@log.Action</td>
                <td>@log.Timestamp.ToString("yyyy-MM-dd HH:mm:ss")</td>
            </tr>
        }
    </tbody>
</table>